Added UwU channel
ThatRedKite/thatkitebot pull request #53
Opened 2022-07-29 20:21 UTC by woo200

When you use /uwu_channel or +uwu_channel it will add a channel, where everything in that channel is uwuified via a webhook

2022-07-29 20:39 UTC, diminDDL requested changes
Move all the uwu stuff in to the uwu cog please.

2022-07-29 20:40 UTC, woo200 commented
> Move all the uwu stuff in to the uwu cog please.

ironic because I initially had it all in the uwu cog but then i thought it looked weird so I moved it to funstuff :\

2022-07-29 20:43 UTC, diminDDL approved these changes
Seems legit

2022-07-30 00:33 UTC, ThatRedKite requested changes
please dont delete the `__init__.py`

2022-07-30 05:40 UTC, woo200 commented on thatkitebot/cogs/uwucog.py
> -class UwuCog(commands.Cog, name=""):
Name was set to "" which caused help command to fail when it tried to send the empty name in a discord embed

2022-07-30 05:46 UTC, ThatRedKite approved these changes
This is a horrible idea but here you go

2022-07-30 05:47 UTC, merged